"""this document generated by internal module from yurlungur."""


def AttackSkill(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Attribute(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def DynamicProxy(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def HealSkill(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def HogeMeta(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def MetaYNode(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def MetaYObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def MetaYParm(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def PoisonSkill(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Property(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractEventDispatcher(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractGraphicsShapeItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractItemDelegate(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractItemModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractItemView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractListModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractProxyModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractScrollArea(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractSlider(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractSpinBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractTableModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAbstractTextDocumentLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QAction(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QActionEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QActionGroup(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QApplication(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBasicTimer(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBitArray(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBitmap(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBoxLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBrush(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QBuffer(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QButtonGroup(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QByteArray(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QByteArrayMatcher(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCalendarWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCheckBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QChildEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QClipboard(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCloseEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QColor(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QColorDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QColumnView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QComboBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCommandLinkButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCompleter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QConicalGradient(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QContextMenuEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCoreApplication(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCryptographicHash(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QCursor(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDataStream(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDataWidgetMapper(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDate(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDateEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDateTime(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDateTimeEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDesktopServices(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDesktopWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDial(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDialogButtonBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDir(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDirIterator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDirModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDockWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDoubleSpinBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDoubleValidator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDrag(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDragEnterEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDragLeaveEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDragMoveEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDropEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QDynamicPropertyChangeEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QErrorMessage(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QEventLoop(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFile(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileIconProvider(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileInfo(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileOpenEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileSystemModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFileSystemWatcher(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFocusEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFocusFrame(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFont(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontComboBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontDatabase(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontInfo(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontMetrics(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFontMetricsF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFormLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QFrame(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGenericArgument(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGenericReturnArgument(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGradient(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsEllipseItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsGridLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsItemGroup(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsLayoutItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsLineItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsLinearLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsPathItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsPixmapItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsPolygonItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsProxyWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsRectItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsScene(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneContextMenuEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneDragDropEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneHelpEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneHoverEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneMouseEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneMoveEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneResizeEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSceneWheelEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsSimpleTextItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsTextItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGraphicsWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGridLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QGroupBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QHBoxLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QHeaderView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QHelpEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QHideEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QHoverEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QIODevice(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QIcon(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QIconDragEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QIconEngine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QImage(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QImageIOHandler(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QImageReader(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QImageWriter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QInputDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QInputEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QInputMethodEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QIntValidator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemDelegate(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemEditorCreatorBase(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemEditorFactory(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemSelection(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemSelectionModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QItemSelectionRange(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QKeyEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QKeySequence(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLCDNumber(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLabel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLayoutItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLibraryInfo(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLineEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLineF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLinearGradient(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QListView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QListWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QListWidgetItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QLocale(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMainWindow(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMdiArea(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMdiSubWindow(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMenu(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMenuBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMessageBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMetaClassInfo(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMetaEnum(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMetaMethod(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMetaObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMetaProperty(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMimeData(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QModelIndex(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMouseEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMoveEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMovie(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMutex(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QMutexLocker(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPaintDevice(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPaintEngine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPaintEngineState(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPaintEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPainter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPainterPath(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPainterPathStroker(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPalette(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPen(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPersistentModelIndex(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPicture(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPictureIO(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPixmap(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPixmapCache(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPlainTextDocumentLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPlainTextEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPluginLoader(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPoint(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPointF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPolygon(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPolygonF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QProcess(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QProgressBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QProgressDialog(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QPushButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRadialGradient(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRadioButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QReadLocker(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QReadWriteLock(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRect(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRectF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRegExp(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRegExpValidator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRegion(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QResizeEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QResource(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRubberBand(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QRunnable(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QScrollArea(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QScrollBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSemaphore(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSessionManager(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSettings(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QShortcut(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QShortcutEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QShowEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSignalMapper(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSize(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSizeF(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSizeGrip(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSizePolicy(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSlider(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSocketNotifier(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSortFilterProxyModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSpacerItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSpinBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSplashScreen(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSplitter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSplitterHandle(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStackedLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStackedWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStandardItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStandardItemModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStatusBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStatusTipEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStringListModel(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyle(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleFactory(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleHintReturn(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleHintReturnMask(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleHintReturnVariant(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOption(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionComboBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionComplex(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionDockWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionFocusRect(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionFrame(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionGraphicsItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionGroupBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionHeader(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionMenuItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionProgressBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionRubberBand(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionSizeGrip(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionSlider(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionSpinBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionTab(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionTabBarBase(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionTabWidgetFrame(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionTitleBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionToolBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionToolBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionToolButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyleOptionViewItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStylePainter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QStyledItemDelegate(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSyntaxHighlighter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSysInfo(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSystemSemaphore(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QSystemTrayIcon(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QT_TRANSLATE_NOOP(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QT_TR_NOOP(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QT_TR_NOOP_UTF8(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTabBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTabWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTableView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTableWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTableWidgetItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTableWidgetSelectionRange(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTabletEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTemporaryFile(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBlock(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBlockFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBlockGroup(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBlockUserData(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBoundaryFinder(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextBrowser(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextCharFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextCodec(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextCursor(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextDecoder(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextDocument(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextDocumentFragment(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextEncoder(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextFragment(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextFrame(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextFrameFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextImageFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextInlineObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextLength(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextLine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextList(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextListFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextObjectInterface(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextOption(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextStream(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextStreamManipulator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextTable(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextTableCell(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextTableCellFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTextTableFormat(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QThread(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QThreadPool(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTime(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTimeEdit(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTimeLine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTimer(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTimerEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QToolBar(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QToolBox(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QToolButton(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QToolTip(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTransform(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTranslator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTreeView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTreeWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTreeWidgetItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QTreeWidgetItemIterator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QUndoCommand(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QUndoGroup(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QUndoStack(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QUndoView(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QUrl(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QVBoxLayout(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QValidator(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWaitCondition(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWhatsThis(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWhatsThisClickedEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWheelEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWidget(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWidgetAction(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWidgetItem(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWindowStateChangeEvent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWizard(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWizardPage(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QWriteLocker(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamAttribute(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamAttributes(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamEntityDeclaration(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamEntityResolver(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamNamespaceDeclaration(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamNotationDeclaration(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamReader(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QXmlStreamWriter(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Qt(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtCriticalMsg(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtDebugMsg(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtFatalMsg(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtMsgType(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtSystemMsg(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def QtWarningMsg(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Signal(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def SkillMeta(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Skills(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def Slot(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YException(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YFile(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YNode(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YNotsupportException(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YObject(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def YParm(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def app(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def application(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def cd(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def children(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def cmd(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def command(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def context(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def dark(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def glob(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def inspect(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def ls(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def max_protect_window(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def maya_main_window(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def os(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def parent(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def pwd(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qAbs(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qAddPostRoutine(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qAlpha(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qBlue(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qChecksum(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qCritical(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qDebug(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qFatal(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qFuzzyCompare(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qGray(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qGreen(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qIsFinite(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qIsGray(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qIsInf(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qIsNaN(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qIsNull(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qRed(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qRegisterResourceData(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qRgb(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qRgba(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qUnregisterResourceData(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qVersion(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qWarning(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qrand(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def qsrand(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def root(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def select(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def show(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def standalone(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def sys(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def traceback(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def unicode(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def wrapper(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

def yqt(*args, **kwargs):
   """str(object) -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object."""
   pass

